#pragma once
#include <cstdint>

enum class FieldKey : uint32_t { // NOLINT
    PLAYER_INVENTORY,
    PLAYER_OUTFIT_LOADOUT,
    PLAYER_WEAPON_LOADOUT,
    PLAYER_DATA,
    PROFILE_DATA,
    PLAYER_LEGACY_DATA,
    PARTY_EXTRA_BROADCAST_INFO,
    PARTY_MEMBERS,
    PARTY_PRIVATE_EXTRA_BROADCAST_INFO,
    PLAYER_PRESENCE,
    FRIENDS_LIST,
    NOTIFICATION_DATA
};