name: build.yml
on:
  push:
    branches: ["gh-readonly-queue*"]
  pull_request:

jobs:
  build-ubuntu:
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build curl zip unzip tar autoconf autoconf-archive automake libtool linux-libc-dev pkg-config software-properties-common lsb-release nasm bison flex python3 python3.12-venv libx11-dev libxext-dev libxrender-dev libxtst-dev libxrandr-dev libltdl-dev libxi-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libvulkan-dev libwayland-dev libxkbcommon-dev libssl-dev libbz2-dev liblzma-dev libudev-dev libdrm-dev libglfw3-dev libgtk-3-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev curl '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libegl1-mesa-dev
          sudo curl -fsSL https://apt.kitware.com/keys/kitware-archive-latest.asc -o /usr/share/keyrings/kitware-archive-keyring.asc
          echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.asc] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/kitware.list  
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Create auth.json
        shell: bash
        run: |
          echo "{\"steamApiKey\": \"${{ secrets.STEAM_API_KEY }}\"}" > auth.json

      - name: Get vcpkg commit
        id: vcpkgcommit
        shell: bash
        run: |
          cd vcpkg
          sha=$(git rev-parse HEAD)
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: Cache vcpkg archives directory
        uses: actions/cache@v4
        with:
          path: ~/.cache/vcpkg/archives
          key: ${{ runner.os }}-vcpkg-deps-${{steps.vcpkgcommit.outputs.sha}}-${{hashFiles('vcpkg.json')}}
          restore-keys: |
            ${{ runner.os }}-vcpkg-deps-${{steps.vcpkgcommit.outputs.sha}}
          fail-on-cache-miss: ${{runner.environment != 'self-hosted'}}
          enableCrossOsArchive: true
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Configure ${{matrix.build_type}} ${{matrix.os}}
        run: |
          /usr/bin/cmake . --preset x64-${{matrix.build_type}}-linux

      - name: Build ${{matrix.build_type}} ${{matrix.os}}
        run: /usr/bin/cmake --build out/build/x64-${{matrix.build_type}}-linux

      - name: Create artifact
        shell: bash
        run: |
          mkdir package
          cp -r out/build/x64-${{matrix.build_type}}-linux/* package/
          rm -f package/*.h
          rm -f package/*.cc
          rm -rf package/.cmake
          rm -f package/*.cmake
          rm -rf package/CMakeFiles
          rm -f package/*.log
          rm -rf package/vcpkg_installed
          rm -f package/auth.json
          rm -f package/build.ninja
          rm -f package/compile_commands.json
          rm -f package/CMakeCache.txt
          rm -rf package/CMakeFiles
          rm -f package/*.ilk
          rm -f package/*.pdb
          (
            cd package
            find . -type d -name CMakeFiles -print0 |
            while IFS= read -r -d '' dir; do
              parent="$(dirname "$dir")"
              echo "Processing: $parent"
              rm -rf $parent/CMakeFiles
              rm -f $parent/*.cmake
              rm -f $parent/*.ilk
              rm -f $parent/*.pdb
              rm -f $parent/*.json
            done
          )

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x64-${{matrix.build_type}}-linux
          path: package/
          retention-days: 1

      - name: Clean up vcpkg folder
        shell: bash
        run: |
          rm -rf ./vcpkg/buildtrees
          rm -rf ./vcpkg/downloads
          rm -rf ./vcpkg/packages

  build-windows:
      runs-on: windows-latest
      strategy:
        fail-fast: false
        matrix:
          build_type: [debug, release]
      steps:
        - name: Clone repo
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Ensure CMake and Ninja are installed
          shell: powershell
          run: |
            choco install cmake ninja -y --force
            echo "C:\Program Files\CMake\bin" >> $GITHUB_PATH
            echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

        - name: Setup MSVC
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: x64

        - name: Resolve LOCALAPPDATA
          id: localappdata
          shell: powershell
          run: |
            echo "value=$env:LOCALAPPDATA" >> $env:GITHUB_OUTPUT

        - name: Get vcpkg commit
          id: vcpkgcommit
          shell: pwsh
          run: |
            Set-Location vcpkg
            $sha = git rev-parse HEAD
            "sha=$sha" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

        - name: Create auth.json
          shell: pwsh
          run: |
            $content = @{
              steamApiKey = "${{ secrets.STEAM_API_KEY }}"
            } | ConvertTo-Json -Compress
            
            Set-Content -Path auth.json -Value $content -Encoding UTF8

        - name: Cache vcpkg archives directory
          uses: actions/cache@v4
          id: vcpkgcache
          with:
            path: ${{steps.localappdata.outputs.value}}\vcpkg\archives
            key: ${{ runner.os }}-vcpkg-deps-${{steps.vcpkgcommit.outputs.sha}}-${{hashFiles('vcpkg.json')}}
            restore-keys: |
              ${{ runner.os }}-vcpkg-deps-${{steps.vcpkgcommit.outputs.sha}}
            fail-on-cache-miss: ${{runner.environment != 'self-hosted'}}
            enableCrossOsArchive: true
          env:
            ACTIONS_STEP_DEBUG: true

        - name: Configure and build ${{matrix.build_type}}
          run: cmake . --preset x64-${{matrix.build_type}}-win

        - name: Build ${{matrix.build_type}}
          run: cmake --build out/build/x64-${{matrix.build_type}}-win

        - name: Make package
          shell: pwsh
          run: |
            New-Item -ItemType Directory -Force -Path "package" | Out-Null
    
            Copy-Item -Recurse -Force "out/build/x64-${{matrix.build_type}}-win/*" "package/"
    
            Remove-Item -Force -ErrorAction SilentlyContinue `
            package\*.h,
            package\*.cc,
            package\*.cmake,
            package\*.log,
            package\*.ilk,
            package\*.pdb,
            package\auth.json,
            package\build.ninja,
            package\compile_commands.json,
            package\CMakeCache.txt
    
            Remove-Item -Recurse -Force -ErrorAction SilentlyContinue `
            package\.cmake,
            package\CMakeFiles,
            package\vcpkg_installed
    
            Get-ChildItem -Recurse -Directory -Filter "CMakeFiles" -Path "package" | ForEach-Object {
              $parent = $_.Parent.FullName
              Write-Host "Processing: $parent"
              Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $_.FullName
              Remove-Item -Force -ErrorAction SilentlyContinue `
              (Join-Path $parent "*.cmake"),
              (Join-Path $parent "*.ilk"),
              (Join-Path $parent "*.pdb"),
              (Join-Path $parent "*.json")
            }

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: x64-${{matrix.build_type}}-win
            path: package/
            retention-days: 1

        - name: Clean up vcpkg folder
          shell: powershell
          run: |
            Remove-Item C:\b -Recurse -Force
            Remove-Item C:\d -Recurse -Force
            Remove-Item C:\p -Recurse -Force

#  test-ubuntu:
#    needs: build-ubuntu
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        build_type: [debug, release]
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: x64-${{matrix.build_type}}-linux
#          path: build/
#
#      - name: Run tests
#        run: |
#          chmod +x build/tests/tests
#          chmod +x build/pragmabackend
#          cd build/tests
#          ./tests
#
#  test-windows:
#    needs: build-windows
#    runs-on: windows-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        build_type: [debug, release]
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: x64-${{matrix.build_type}}-win
#          path: build/
#
#      - name: Create auth.json
#        shell: bash
#        run: |
#          echo "{\"steamApiKey\": \"${{ secrets.STEAM_API_KEY }}\"}" > build/auth.json
#
#      - name: Run tests
#        shell: cmd
#        run: |
#          cd build\tests\
#          .\tests.exe
